-- Create jackpot table
CREATE TABLE jackpot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    initial_pool_value NUMERIC(19,2) NOT NULL,
    current_pool_value NUMERIC(19,2) NOT NULL,
    contribution_type VARCHAR(20) NOT NULL CHECK (contribution_type IN ('FIXED', 'VARIABLE')),
    contribution_percentage DOUBLE,
    contribution_decay_rate DOUBLE,
    reward_type VARCHAR(20) NOT NULL CHECK (reward_type IN ('FIXED', 'VARIABLE')),
    reward_percentage DOUBLE,
    reward_pool_limit NUMERIC(19,2),
    version BIGINT,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL
);

-- Create jackpot_contribution table
CREATE TABLE jackpot_contribution (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bet_id VARCHAR(255) NOT NULL UNIQUE,
    user_id VARCHAR(255) NOT NULL,
    jackpot_id BIGINT NOT NULL,
    stake_amount NUMERIC(19,2) NOT NULL,
    contribution_amount NUMERIC(19,2) NOT NULL,
    current_jackpot_amount NUMERIC(19,2) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    FOREIGN KEY (jackpot_id) REFERENCES jackpot(id)
);

-- Create jackpot_reward table
CREATE TABLE jackpot_reward (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bet_id VARCHAR(255) NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    jackpot_id BIGINT NOT NULL,
    jackpot_reward_amount NUMERIC(19,2) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    FOREIGN KEY (jackpot_id) REFERENCES jackpot(id)
);

-- Create indexes for better query performance
CREATE INDEX idx_jackpot_contribution_bet_id ON jackpot_contribution(bet_id);
CREATE INDEX idx_jackpot_contribution_jackpot_id ON jackpot_contribution(jackpot_id);
CREATE INDEX idx_jackpot_reward_bet_id ON jackpot_reward(bet_id);
CREATE INDEX idx_jackpot_reward_jackpot_id ON jackpot_reward(jackpot_id);
